default:
  tags:
    - runner

variables:
  RISCV: /opt/riscv
  BITSTREAM: kmh-v1
  SBI: opensbi

stages:
    - compile

kernel-job:
  stage: compile
  variables:
    ARCH: riscv
    CROSS_COMPILE: riscv64-unknown-linux-gnu-
  script:
    - export PATH=$PATH:$RISCV/bin
    - mkdir -p builds
    - rm builds/* -rf
    - make defconfig xiangshan.config
    - make -j 64
    - cp arch/riscv/boot builds -rf
  artifacts:
    paths:
    - builds/

